---
title: "M4A_Project"
author: "Ross Pingatore"
date: "10/30/2020"
output: pdf_document
---

```{r, message=FALSE, warning=FALSE,echo=FALSE}
library(readxl)
medicare_for_all_1 <- read_excel("Data/medicare_for_all_1.xlsx")
single_payer_system_1 <- read_excel("Data/single_payer_system_1.xlsx")
universal_health_care_1 <- read_excel("Data/universal_health_care_1.xlsx")
medicare_for_all_2 <- read_excel("Data/medicare_for_all_2.xlsx")
single_payer_system_2 <- read_excel("Data/single_payer_system_2.xlsx")
universal_health_care_2 <- read_excel("Data/universal_health_care_2.xlsx")
medicare_for_all_3 <- read_excel("Data/medicare_for_all_3.xlsx")
single_payer_system_3 <- read_excel("Data/single_payer_system_3.xlsx")
universal_health_care_3 <- read_excel("Data/universal_health_care_3.xlsx")
medicare_for_all_4 <- read_excel("Data/medicare_for_all_4.xlsx")
single_payer_system_4 <- read_excel("Data/single_payer_system_4.xlsx")
universal_health_care_4 <- read_excel("Data/universal_health_care_4.xlsx")

```


```{r, echo=FALSE}
suppressPackageStartupMessages(library(tidyverse))
merged_data <- bind_rows(medicare_for_all_1,single_payer_system_1,universal_health_care_1,medicare_for_all_2,single_payer_system_2,universal_health_care_2,medicare_for_all_3,single_payer_system_3,universal_health_care_3,medicare_for_all_4,single_payer_system_4,universal_health_care_4)

dim(merged_data)
merged_data[!duplicated(merged_data$Text),] -> merged_data
dim(merged_data)
write_excel_csv(merged_data, 'Data/merged_data.xlsx')
view(merged_data)
```

```{r, eval=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
unique(merged_data$Language)
```

```{r, working with the text, fig.width=14, fig.height=4.5, echo=FALSE, warning=FALSE, message=FALSE}
library(tidytext)
library(tm)
library(dplyr)
#https://stackoverflow.com/questions/36824296/r-remove-specific-word-in-a-txte-like-the-this

corpus <- Corpus(VectorSource(merged_data$Text))
time <- Corpus(VectorSource(merged_data$`Created At`))

corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, removeNumbers)
corpus <- tm_map(corpus, tolower)
corpus <- tm_map(corpus, removeWords, stopwords("english")) 
corpus <- tm_map(corpus, stripWhitespace)
corpus <- tm_map(corpus, stemDocument)


doc_matrix <- TermDocumentMatrix(corpus)
doc_matrix_m <- as.matrix(doc_matrix)
doc_matrix_val <- sort(rowSums(doc_matrix_m), decreasing = T)
doc_matrix_df <- data.frame(word = names(doc_matrix_val), freq = doc_matrix_val)

top_15 <- head(doc_matrix_df, 15)
top_15
```

```{r, bar chart, echo=FALSE, fig.width=10}
top_15%>%
  ggplot(aes(reorder(word,freq), freq)) + geom_bar(stat = "identity") + xlab("Term") + ylab("Frequency") + labs(title = "Most Frequent Terms Within Tweets Relating to Medicare For All")

```

```{r, associations, echo=FALSE}
findAssocs(doc_matrix, terms = c('health','care','system', 'biden', 'trump'), corlimit = 0.25)
```

```{r, sentiment scores, warning=F, message=FALSE, echo=FALSE}
df_sentiment <- data_frame(text = character(), positive = double(), negative = double(), date = character())

for(index in seq_along(corpus)){
  tweet <- corpus[[index]]$content
  ts <- time[[index]]$content
  tokens <- data_frame(text = tweet) %>% unnest_tokens(word,text)
  tokens%>%
     inner_join(get_sentiments("bing"))%>%
    count(sentiment)%>%
    spread(sentiment, n, fill = 0) -> rating
  if (ncol(rating) == 0){
    next()
  }
  if (ncol(rating) == 1){
    var_1 = names(rating[1])
    if(var_1 == 'positive'){
      rat = rating$positive
      df_sentiment%>%
        add_row(positive = rat, text = tweet, date = ts) -> df_sentiment
    }
    if(var_1 == 'negative'){
      rat = rating$negative
      df_sentiment%>%
        add_row(negative = rat, text = tweet, date = ts) -> df_sentiment
    }
  }
  
  if (ncol(rating) == 2) {
    df_sentiment%>%
      add_row(negative = rating$negative, positive = rating$positive, text = tweet, date = ts) -> df_sentiment
  }
}
```


```{r, df_sentiment processing, warning=FALSE, message=FALSE, echo=FALSE}
df_sentiment%>%
  replace_na(list(positive = 0, negative = 0, text = "Blank")) -> df_sentiment

df_sentiment%>%
  mutate(total = positive - negative) -> df_sentiment

df_sentiment[!duplicated(df_sentiment$text),] -> df_sentiment
write_excel_csv(df_sentiment, 'Data/sentiment_scores.xlsx')
```


```{r, sentiment score visualization, warning=FALSE, message=FALSE, echo=FALSE, fig.width=10}
df_sentiment%>%
  mutate(fill_total = factor(total, levels = unique(total), ordered = T),
    fill_col = case_when(
      total > 0 ~ "green",
      total < 0 ~ "red",
      TRUE ~ "grey"
    )) -> df_sentiment

df_sentiment%>%
  ggplot(aes(total, fill = fill_col)) + labs(title = "Distribution of Sentiment Towards Medicare For All", x = 'Sentiment Rating (5 Highly Positive, -5 Highly Negative)', y = "Number of Tweets") + theme(plot.title = element_text(hjust = 0.5)) -> fig_1

attach(df_sentiment)
palt <- c('Support' = ' green' , 'Neutral' = 'grey', 'Dislike' = 'red')

fig_1 + geom_histogram() + labs(fill = "Sentiment") + scale_fill_identity(guide = "legend", labels = c("Favor", "Neutral", "Dislike"))
fig_1 + geom_density() + labs(fill = "Sentiment") + scale_fill_identity(guide = "legend", labels = c("Favor", "Neutral", "Dislike"))

summary(df_sentiment$total)



```
```{r, sentiment analysis continued, echo=FALSE}
df_sentiment%>%
  filter(total > 0)%>%
  nrow() -> favor

df_sentiment%>%
  filter(total < 0)%>%
  nrow() -> dislike

df_sentiment%>%
  filter(total == 0)%>%
  nrow() -> neutral

number_of_tweets <- data_frame(Favor = favor, Neutral = neutral, Dislike = dislike)

total <- favor + dislike + neutral
# Percentages
percentages <- data_frame(Favor = favor / total, Neutral = neutral / total, Dislike = dislike / total) * 100

```

```{r}
number_of_tweets
percentages
```

```{r, echo=FALSE, fig.width=10}
library(plotrix)
slices <- c(percentages$Favor, percentages$Neutral, percentages$Dislike)
lab <- names(percentages)

paste(round(percentages$Favor),'%','Favor') -> fv 
paste(round(percentages$Neutral),'%','Neutral') -> nt
paste(round(percentages$Dislike),'%','Dislike') -> dl



pie3D(slices, labels = c(fv,nt,dl), col = c("green", "grey","red"),  main = "Attitudes Towards Medicare For All Based on Tweets", border = "black", theta = .8, explode = .2, labelcex = 1.7, radius = 0.83)

view(df_sentiment)
```

